name: npm publish

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.0"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm install
      # - name: Run tests
      #   run: npm test
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.MEDUSA_STRAPI_PLUGIN_TOKEN }}
